# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-31 06:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_basic_info_validdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basic_info',
            old_name='validdata',
            new_name='validdate',
        ),
    ]
