# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-31 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic_info',
            name='validdata',
            field=models.CharField(default='20150101-20190730', max_length=17),
        ),
    ]
